---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: rendu
data:
  config.json: |
    {
      "message": "Hello there sans rebuild"
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: rendu
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-node
        image: dperreaux/tp-k8s:v1
        ports:
            - containerPort: 3000
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
      volumes:
      - name: config-volume
        configMap:
          name: app-config